name: docker-ci

on:
  pull_request:

jobs:
  docker-ci:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata action
        id: meta
        uses: docker/metadata-action@v5
        with:
          images:
            zammad-local
          tags: |
            type=raw,latest

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          pull: true
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/zammad-local.tar

      - name: Checkout docker compose files
        uses: actions/checkout@v4
        with:
          repository: zammad/zammad-docker-compose
          path: zammad-docker-compose

      - name: Run docker compose tests
        run: |
          cd zammad-docker-compose
          docker load --input /tmp/zammad-local.tar

          cat - <<ENV_FILE >> .env
          IMAGE_REPO=zammad-local
          VERSION=latest
          ENV_FILE

          docker compose -f docker-compose.yml up --detach
          docker compose cp .github/auto_wizard.json zammad-railsserver:/opt/zammad/tmp
          .github/tests.sh
