name: build-fork-image
on:
  push:
    branches: [ develop-sunnys, stable ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.fork
          push: true
          tags: |
            ghcr.io/sunnys-creations/sunnys-tickets:develop-sunnys
            ghcr.io/sunnys-creations/sunnys-tickets:${{ github.ref_name }}